easy_admin:
  site_name: '<img src="/images/chmkms-logo.png" height="100px" />'
  list: 
    title: '%%entity_label%%'
    actions: 
        # - { name: 'show', icon: 'eye', label: ''}
        # - { name: 'edit', icon: 'pencil', label: 'Edit'}
        # - { name: 'delete', icon: 'trash', label: '' }
        # - { name: 'search', icon: 'search', label: 'Search'}
        # - { name: 'new', icon: 'plus-square', label: 'New'}
  entities:
    Classes:
      class: App\Entity\OnlineClass
      label: 'Media'
      list:
        fields: ['id','name','description','videoURL','isLive','isListed','videoLength','voiceType']
    # Class_12:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 12'
    #   list:
    #     dql_filter: "entity.class = '12'"
    # Class_11:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 11'
    #   list:
    #     dql_filter: "entity.class = '11'"
    # Class_10:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 10'
    #   list:
    #     dql_filter: "entity.class = '10'"
    # Class_9:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 9'
    #   list:
    #     dql_filter: "entity.class = '9'"
    # Class_8:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 8'
    #   list:
    #     dql_filter: "entity.class = '8'"
    # Class_7:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 7'
    #   list:
    #     dql_filter: "entity.class = '7'"
    # Class_6:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 6'
    #   list:
    #     dql_filter: "entity.class = '6'"
    # Class_5:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 5'
    #   list:
    #     dql_filter: "entity.class = '5'"
    # Class_4:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 4'
    #   list:
    #     dql_filter: "entity.class = '4'"
    # Class_3:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 3'
    #   list:
    #     dql_filter: "entity.class = '3'"
    # Class_2:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 2'
    #   list:
    #     dql_filter: "entity.class = '2'"
    # Class_1:
    #   class: App\Entity\OnlineClass
    #   label: 'Class 1'
    #   list:
    #     dql_filter: "entity.class = '1'"